# -*- coding: utf-8 -*-
"""PRODIGY_DS_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQrkrW0PYMmF_oeNsiFZqJqcOfwfD6ow
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Load the dataset
data = pd.read_csv("/content/datasets/twitter_training.csv")
print(data)
print(data.info())

#By using TextBlob python library
from textblob import TextBlob

#function to perform sentiment analysis
def get_sentiment(text):
  analysis = TextBlob(str(text))
  return analysis.sentiment.polarity


#Apply sentiment analysis
data['sentiment'] = data['Borderlands'].apply(get_sentiment)

from sqlalchemy.sql.selectable import TypedReturnsRows
# Example import for SQLAlchemy 1.3
from sqlalchemy.sql.selectable import Select

#1.Histogram
plt.figure(figsize=(8, 6))
sns.histplot(data['sentiment'], bins=30, kde=True)
plt.title('Sentiment Distribution')
plt.xlabel('2401')
plt.ylabel('Positive')
plt.show()